
import os
from flask import Flask, send_from_directory, request, jsonify
from syqlorix import Page
import sys

app = Flask(__name__)

base_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(base_dir)
frontend_dir = os.path.join(project_root, 'frontend')

syqlorix_path = os.path.join(os.path.dirname(project_root), 'Syqlorix')
if os.path.exists(syqlorix_path) and os.path.isdir(syqlorix_path):
    if syqlorix_path not in sys.path:
        sys.path.insert(0, syqlorix_path)
        try:
            import syqlorix as _
        except ImportError:
            print(f"Warning: Could not import Syqlorix from {syqlorix_path}. "
                  "Ensure it's installed or correctly located.", file=sys.stderr)
# ----------------------------------------------------------------------

@app.route('/')
def serve_index():
    return send_from_directory(frontend_dir, 'index.html')

@app.route('/<path:filename>')
def serve_static(filename):
    return send_from_directory(frontend_dir, filename)

@app.route('/generate_code', methods=['POST'])
def generate_code():
    design_data = request.json
    
    page = Page(title="Generated Syqlorix Page")
    with page.body:
        page.h1("Hello from Syqlorix Canvas!")
        page.p(f"You sent: {design_data.get('message', 'No message')}")
        page.p("This page was generated by Syqlorix.")
        page.button("Click Me")
    page.style("body { font-family: sans-serif; background-color: #f8f8f8; }")
    
    generated_syqlorix_code = f"""
from syqlorix import Page

page = Page(title="{design_data.get('title', 'Generated Page')}")

with page.body:
    page.h1("Syqlorix Canvas Generated!")
    page.p("This is Python code exported from the visual editor.")
    page.p(f"Received data: {{design_data}}") 
    page.button("Hello!")

page.style('''
    body {{ font-family: system-ui; background: #e0e0e0; padding: 20px; }}
    h1 {{ color: #0d6efd; }}
''')

html_output = page.render()
"""
# ----------------------------------------------

    return jsonify({
        'syqlorix_code': generated_syqlorix_code,
        'rendered_html': page.render()
    })
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)